mep_adaptive:
  policy_config_path: risky_multipath_subgoal/policy_config/rnn_policy_config.pkl
  featurize_type: ppo
  train: false
mep1:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep2:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep3:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep4:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep5:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep6:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep7:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep8:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep9:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep10:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep11:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
mep12:
  policy_config_path: risky_multipath_subgoal/policy_config/mlp_policy_config.pkl
  featurize_type: ppo
  train: true
